/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "box_2.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

/*
	xdr notation to transfer information to improve interoperatbility,
	converts parameters to passed to server, client and server don't 
	share same address space or pointers, as well as possibly having different
	types of data structures and system [big endian little endian]
*/
	
box_results *
box_calc_2(argp, clnt)
	dimensions *argp;
	CLIENT *clnt;
{
	static box_results clnt_res;
	/*
		xdr_proc in proc encode procedure paramaters [sends 
		dimensions to server] xdr_proc to decode procedures results 
		of server [returns box_results from server], used for 
		marshalling and unmarshalling
	*/
	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, BOX_CALC, xdr_dimensions, argp, xdr_box_results, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

float *
mail_calc_2(argp, clnt)
	mail_dims *argp;
	CLIENT *clnt;
{
	static float clnt_res;
	/*
		xdr_proc in proc encode procedure paramaters [sends 
		mail_dims to server] xdr_proc to decode procedures results 
		of server [returns floating price from server], used for 
		marshalling and unmarshalling
	*/
	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, MAIL_CALC, xdr_mail_dims, argp, xdr_float, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
